### ISSUE TITLE
Using Distributed Tracing Document Discription is not right

### ISSUE THREAD

**Issue by wswind** [SteeltoeOSS/MainSite#10]
## Describe the bug

Using Distributed Tracing  totruial doesn't use Redis service connector, I think this is a document mistake 
<https://steeltoe.io/cloud-management/get-started/distributed-tracing>
![image](https://user-images.githubusercontent.com/18399096/80055954-9662e780-8555-11ea-93bb-58c1bc6fcbb1.png)

**Comment by jkonicki** [comment]
Fixed: https://github.com/SteeltoeOSS/MainSite/commit/5c9ca5152495ac849a42e2c9a8307e33f67b4750
