### ISSUE TITLE
Error Finding SteeltoeWebApplication

### ISSUE THREAD

**Issue by kzawad1** [SteeltoeOSS/MainSite#113]
## Describe the bug
Following example located on Steeltoe website under the Steeltoe Workshop specifically "Adding a cloud connector with SQL" and getting error:
https://docs.steeltoe.io/guides/get-to-know-steeltoe/exercise3.html?tabs=visual-studio%2CVisual-Studio-LocalDB

The error is:
```
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0246	The type or namespace name 'SteeltoeWebApplication' could not be found (are you missing a using directive or an assembly reference?)	WebApplication1	zzzz\WebApplication1\WebApplication1\Controllers\TodoItemsController.cs	3	Active
```
 

## Steps to reproduce 
1. Follow the steps in: https://docs.steeltoe.io/guides/get-to-know-steeltoe/index.html
2. The error shows up when adding database connection: https://docs.steeltoe.io/guides/get-to-know-steeltoe/exercise3.html?tabs=visual-studio%2CVisual-Studio-LocalDB

## Expected behavior
Since I am following the example, there shouldn't be any compile errors.

## Environment (please complete the following information):
 - Steeltoe Version: 3.2.1
 - Platform: Azure
 - OS: Windows 10 Pro 
 - .NET Version: .NET 6
 - Any other library versions to note

**Comment by TimHess** [comment]
The `SteeltoeWebApplication` namespace only exists in this guide, and is a typo (it should match the name given to the project when it is created). The guide should be updated to either use `WebApplication1` here or `SteeltoeWebApplication` everywhere

**Comment by kzawad1** [comment]
@TimHess thanks for verifying. 

Needed to do a couple of things to get it building & running:

1. Update application namespace in **ToDoItemsController.cs**:
Replace:
   `using SteeltoeWebApplication.Models;`
With:
  `using WebApplication1.Models;`

3. Resolve compile error with AddDbContect in Program.cs
Replace:
    `builder.Services.AddDbContext<Models.TodoDbContext>(options => options.UseSqlServer(builder.Configuration));`
With:
   `builder.Services.AddDbContext<WebApplication1.Models.TodoDbContext>(options => options.UseSqlServer(builder.Configuration));`
5. Local database connection.
Run the commands in this link:
https://www.jetbrains.com/help/datagrip/connecting-to-sql-server-express-localdb.html
Had to install SQL Server Management Studio (SSMS).  
https://stackoverflow.com/questions/36157191/sql-server-how-to-find-all-localdb-instance-names
Update the file appsettings.json:
```
  "sqlserver": {
    "credentials": {
      "ConnectionString": "Server=(localdb)\\mssqllocaldb;database=Steeltoe;Trusted_Connection=True;"
      //"server": #SQL_SERVER_ADDRESS#,
      //"port": #SQL_SERVER_PORT#,
      //"username": #SQL_SERVER_USERNAME#,
      //"password": #SQL_SERVER_PASSWORD#,
      //"database": #SQL_SERVER_DATABASE#
    }
  }
```
6. After that ran it and got a few runtime errors that pertained to missing Nuget packages


I was able to finish the exercise.

**Comment by kzawad1** [comment]
Issue was resolved.
