### ISSUE TITLE
Anchors for headings with periods in them need to be handled differently

### ISSUE THREAD

**Issue by jkonicki** [SteeltoeOSS/MainSite#13]
The anchors are based on the titles of the headings in markdown/html.  Unfortunately, a period in the name. For example "ASP.NET blah blahh" will have an id = "asp.net-blah-blahh".  When selecting this, it will not resolve to the anchor. 

`id` attribute is supposed to work with a period, but it doesn't with this site. 

One (best) option is to figure out why it isn't working, another option is to ignore the `.` for `id` attribute and have it `id="aspnet-blah-blahh"`.

**Comment by ddieruf** [comment]
Fixed with new docs site
