### ISSUE TITLE
Steeltoe Dynamic logging page returning 400

### ISSUE THREAD

**Issue by thatstatsguy** [SteeltoeOSS/MainSite#140]
When I navigate to the Steeltoe Dynamic Logging Via the Projects drop down (or via the footer) I'm redirected to a page which can't be found.

The URL in question
https://steeltoe.io/docs/logging

Steps to reproduce

Navigate to home page
On the ribbon click projects, click Steeltoe Dynamic Logging
Should see 400 response
Expected behavior
To see the Docs :)

Environment (please complete the following information, if applicable):
Platform:
OS Version: Windows 10
Browser: Edge

**Comment by bart-vmware** [comment]
Hi @thatstatsguy, thanks for reporting. I can reproduce the issue in Chrome as well.

@TimHess To clarify, "navigate to the homepage" means going to https://steeltoe.io/ (so not the docs site)

**Comment by TimHess** [comment]
Neat, in both cases this is a broken link (should have been to /dynamic-logging) to a product marketing type page that was never finished.  I think I'm just going to remove the link for now, and I'll also see if I can fix the weird dropdown behavior where the menu disappears after your first click and stays open on subsequent clicks
