### ISSUE TITLE
Allow users to create account, ASP identity

### ISSUE THREAD

**Issue by fasteddys** [SteeltoeOSS/MainSite#147]
Hello, using ASP identity allow users to create an account and subscribe to notifications/emails updates.

**Comment by TimHess** [comment]
We will not be adding user accounts to steeltoe.io.

I'd love to have something for you to subscribe to, but we don't currently have the bandwidth to be producing content regularly. If you're interested in updates to Steeltoe, right now the best option is to watch the main [Steeltoe repo](https://github.com/SteeltoeOSS/Steeltoe). If that produces too much noise, you can setup a custom subscription that only notifies you when there are new releases
