### ISSUE TITLE
[ENH] core 8/9,  Asp identity users, roles claims, menu - to roles mgmnt

### ISSUE THREAD

**Issue by ridingmower** [SteeltoeOSS/MainSite#148]
Hello, I have been playing around with steeltoe, and let me be the first to say its a very unique approach and heck off boxes in a unique way, I was using some samples to try it out, would be nice if those had some other basic features.

- [ ] Update to core 8/9
- [ ] Users roles and claims management from the GUI on the main site in the sample including comments on how to use the event driven side of steel toe, for e.g. DDOS or spam event detected and user lockout etc.
- [ ] Switching themes
- [ ] making the app compatible to run actions as mircoservices or serverless functions just be placing and attribute on top
- [ ] integration this - https://github.com/jdanylko/Tuxboard
- [ ] how to do case/docs workflow mgmt and approvals

**Comment by TimHess** [comment]
- Update to core 8/9
   - Moving to .NET8 is well under way in the samples in [this branch](https://github.com/SteeltoeOSS/Samples/tree/latest). Docs work is probably not as far along, but can be found in [this branch](https://github.com/SteeltoeOSS/Documentation/tree/v4)
- Users roles and claims management from the GUI on the main site in the sample including comments on how to use the event driven side of steel toe, for e.g. DDOS or spam event detected and user lockout etc.
   - Unfortunately, Integration/Messaging/Stream components have been [discontinued](https://github.com/SteeltoeOSS/Steeltoe/issues/1244)
- Switching themes
   - Where? We do have some incomplete theme work for steeltoe.io and docs.steeltoe.io, I'm hoping to include that and docfx updates as we wrap up the Steeltoe v4 docs
-  making the app compatible to run actions as mircoservices or serverless functions just be placing and attribute on top
   - It is unclear what this would actually do, and the core Steeltoe team does not have capacity to figure it out in the near term
- integration this - https://github.com/jdanylko/Tuxboard
   - I don't understand the connection
-  how to do case/docs workflow mgmt and approvals
   - I don't understand what you want here
