### ISSUE TITLE
Dropdown menu mouse position trigger is offset

### ISSUE THREAD

**Issue by ccheetham** [SteeltoeOSS/MainSite#16]
The position
 of the mouse on Steeltoe site page that triggers a dropdown menu does not coincide with the location of the menu itself.  In the attached image, the red arrow marks the general position of the mouse that triggers the dropdown menu.  In this specific example, the menu label is "Why Steeltoe."

 - OS Version: OS X 10.15.6
 - Browser: Microsoft Edge 84.0.522.59

![Screen Shot 2020-08-18 at 11 53 32 AM](https://user-images.githubusercontent.com/410767/90536909-acbb3180-e14a-11ea-8ea8-c2ed37d1d539.png)

**Comment by ddieruf** [comment]
Fixed with new navigation that is shared between mainsite and docs site.
