### ISSUE TITLE
Running list of minor issues on website 

### ISSUE THREAD

**Issue by jkonicki** [SteeltoeOSS/MainSite#17]
Create this to keep track of some of the minor issues on the website:

* Whitespace around in the `Why Steeltoe` pulldown menu is off, since the edition of "Event Driven" - See attached pic
* Whitespace around in the `Projects` pulldown menu is off - see attached pic
* Contract is off when using Chrome with DarkMode on the samples - see tweet for picture - https://twitter.com/AHaleIII/status/1298018201096335360
<img width="331" alt="Screen Shot 2020-08-25 at 11 11 31 AM" src="https://user-images.githubusercontent.com/145382/91192333-cec13080-e6c3-11ea-96d2-7a271ff11408.png">
<img width="326" alt="Screen Shot 2020-08-25 at 11 11 21 AM" src="https://user-images.githubusercontent.com/145382/91192373-d8e32f00-e6c3-11ea-8ea2-07002655ddec.png">

**Comment by ddieruf** [comment]
#1 and #2 have been fixed. #3 is a little fuzzy because they are using a theme in their browser to force web pages to a dark mode. The theme has made the page unusable. Not sure this is something we need to account for.
