### ISSUE TITLE
Option to go to Steeltoe Initializr from the main site

### ISSUE THREAD

**Issue by kartiklunkad26** [SteeltoeOSS/MainSite#18]
## Is your feature request related to a problem? Please describe.
I do not have any way to come to start.steeltoe.io unless I know the URL. As I learn about Steeltoe, I need a way to practice my learnings. 

## Describe the solution you'd like
I want the ability to go to start.steeltoe.io from steeltoe.io so that I can practice the patterns I have learnt in Steeltoe Tutorials. Specifically it can be under the Learn tab on steeltoe.io

## Describe alternatives you've considered
Alternative is to go to start.steeltoe.io directly, which is fine unless you don't know about it.

**Comment by jkonicki** [comment]
I would like to see a link to the Steeltoe Initializr under the learn menu.  

What are you thoughts on having the Steeltoe Initializr as a sub-section under the Get Started menu item?  If not a sub-section (not a sub menu), we could have it inline with the rest.

_For example:_
Get Started
   ->  Steeltoe Initializr
Documentation
API Browser
Blog
