### ISSUE TITLE
Doc site root doesn't render style

### ISSUE THREAD

**Issue by ccheetham** [SteeltoeOSS/MainSite#43]
## Describe the bug

Going to doc site root yields site with no style applied.  

## Steps to reproduce 

Go to: 
https://docs.steeltoe.io/

![Screen Shot 2020-11-02 at 8 41 56 AM](https://user-images.githubusercontent.com/410767/97874660-51c7be00-1ce7-11eb-8f42-cfbb74436ee5.png)

**Comment by jkonicki** [comment]
This page needs to be removed and the URL needs to be forwarded.  Same as #45

**Comment by ddieruf** [comment]
An `http-equiv` redirect was added to index.html, which sends someone to the docs home page.
