### ISSUE TITLE
get-started/consul There is an error

### ISSUE THREAD

**Issue by dcdlove** [SteeltoeOSS/MainSite#5]
## Describe the bug
Beginner's Guide Wrong copy or registered service name does not match configuration

## Steps to reproduce 
1.Open page [https://steeltoe.io/service-discovery/get-started/consul](url)
2.  “Consul_Register_Example“ Should be replaced with “Consul-Register-Example ”
3. Because the service name obtained by the client(IDiscoveryClient ) is actually “Consul-Register-Example”

## Environment (please complete the following information):
 - Platform: etc
 - OS:Windows
 - .NET Version .NET Core 3.1.0
 - Steeltoe Version 2.4.0
 - Any other library versions to note

## Additional context or links

![TIM截图20200103145422](https://user-images.githubusercontent.com/10043691/71710844-219a5f00-2e39-11ea-9d39-c8242f239a62.jpg)

![TIM图片20200103145053](https://user-images.githubusercontent.com/10043691/71710688-7d181d00-2e38-11ea-8263-e1f00279e22f.png)
![TIM图片20200103145043](https://user-images.githubusercontent.com/10043691/71710695-830dfe00-2e38-11ea-9c46-84ea24ab2383.png)
![TIM图片20200103145249](https://user-images.githubusercontent.com/10043691/71710752-c7010300-2e38-11ea-9bb5-3ed7d5f278f1.png)

**Comment by ddieruf** [comment]
A fix should be uploaded tonight. Feel free to review on dev - https://dev.steeltoe.io/service-discovery/get-started/consul.
